version: "3.9"
services:
  api:
    image: fitesa-backend:1.0.0
    env_file: [.env]
    ports:
      - target: 8000
        published: ${APP_PORT:-8080}
        mode: ingress
    command: >
      bash -lc "
      alembic -c /app/alembic.ini upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      replicas: 1
      restart_policy: { condition: on-failure }
      resources:
        limits: { cpus: "1.0", memory: 1G }
        reservations: { cpus: "0.25", memory: 256M }
      placement:
        constraints: [ "node.role == manager" ]
